name: Elixir CI

# Define workflow that runs when changes are pushed to the
# `main` branch or pushed to a PR branch that targets the `main`
# branch. Change the branch name if your project uses a
# different name for the main branch like "master" or "production".
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Test on OTP ${{matrix.version.otp}} / Elixir ${{matrix.version.elixir}} / OS ${{matrix.version.os}}
    strategy:
      matrix:
        version:
          [
            { otp: "27", elixir: "1.17.x", os: "ubuntu-latest" },
            { otp: "26", elixir: "1.16.x", os: "ubuntu-latest" },
            { otp: "26", elixir: "1.15.x", os: "ubuntu-latest" },
            { otp: "25", elixir: "1.14.x", os: "ubuntu-22.04" },
            { otp: "24", elixir: "1.13.x", os: "ubuntu-20.04" },
            { otp: "24", elixir: "1.12.x", os: "ubuntu-20.04" },
            { otp: "23", elixir: "1.11.x", os: "ubuntu-20.04" }
          ]
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.version.otp}}
          elixir-version: ${{matrix.version.elixir}}
          version-type: strict

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-

      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Compiles without warnings
        run: mix compile --warnings-as-errors

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run tests
        run: mix test
